services:
  server:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library
